### ISSUE TITLE
DarkPlasma_FaceToStand.Js suggestion for managing X and Y allignment

### ISSUE THREAD

**Issue by RyanBram** [elleonard/RPGtkoolMV-Plugins#10]
Hi, Elleonard.

First of all I want to say thank you very much for creating lots of useful plugins for MV. Your plugins really help me in creating my game.

Second is related to your DarkPlasma_FaceToStand.Js . This plugin open lots of potential for creating VN Game using RPG Maker MV.

![Screenshot](https://user-images.githubusercontent.com/4508389/91212521-88f37f00-e73a-11ea-8538-09ed1fc46473.png)

The first issue that I found when using your plugin is it needs lots of step to display Stand Picture in various X or Y position, because X and Y position is determined by plugin setting, so there is no method to change X and Y position in the middle of the game, am I right?

The second issue is the stand picture position is not flexible enough when I want to change game resolution, because the X and Y is absolute value instead of relative value by looking at `Graphics.width`.

I found a plugin that manage picture position efficiently, especially if we want to manage lots of stand picture on screen, the plugin is here:
[MpiPictureAlignment.zip](https://github.com/elleonard/RPGtkoolMV-Plugins/files/5125643/MpiPictureAlignment.zip)

I can't just use this plugin and your plugin together because of incompatibility issue.

I am sorry for making you reading this long text.

ご清聴ありがとうございました。

宜しくお願いします、
Ryan Bram

**Comment by elleonard** [comment]
Thank you for using my plugin and suggestion.
FaceToStand plugin is really simplified to be easy to use.

1. Will the plugin provide interface to set x and y position in the middle of game?

I'm considering two implementation ways.

a. Adding plugin parameter `Offset x variable` and `Offset y variable` to one by one `Face Image To Stand Image` structure.
b. Providing plugin command `moveCurrentStand x y` and `offsetCurrentStand offsetx offsety` .

I think b is better.

2. Will the plugin provide interface to set x and y position with relative value?

I don't like to make plugin user write code just like `Graphics.boxWidth - 200` because almost user cannot maintenance program code.
So, in my opinion, the plugin should provide just like `From Right Edge Mode` (if user input x = 200, picture position is `Graphics.boxWidth - 200` ).

Are these way to satisfy your wants?

**Comment by RyanBram** [comment]
Hi, Elleonard.
Thank you very much for your reply.

> FaceToStand plugin is really simplified to be easy to use.

I am really agree with you that your plugin are among the easiest of plugins I ever use.

From what I understand, your Face to Stand conversation can be started from the event editor by the following step:
![Picture 1](https://user-images.githubusercontent.com/4508389/91341923-7e052100-e804-11ea-9a69-e9ed177f5bcc.png)

I propose something more simple and more compatible with Leeryonto's StandPictureManager.js like this:
![Picture 2](https://user-images.githubusercontent.com/4508389/91342102-c0c6f900-e804-11ea-8aa0-3c0de002a45f.png)

`StartStandPicture` = Plugin command to replace your Show Stand Mode switch (compatible with Leeryonto's)

`ShowStand` = Plugin command to setup stand picture for next Show Text... command
`1` = Associated Picture ID to replace your Stand Picture Id variable
`FadeLeft` / `FadeRight` / `Fade` = Fade direction to replace your Right Fade Switch
`Left` / `Right` / `Center` = to determine where is the position of next Stand Picture

Maybe the `Left` / `Right` / `Center` position can be added with x offset variable, such as `Center +100` or `Center -100`

To improve further compatibility with Leeryonto's StandPictureManager.js maybe the following setup can be added in your plugin setup:
![Picture 3](https://user-images.githubusercontent.com/4508389/91344777-9d9e4880-e808-11ea-99b2-ece799721011.png)

Stand Picture Name can be filled with Character Name or using Character ID code, therefore it can be used to automatically show character name in message box and also will be compatible with Leeryonto's plugin command `StandPictureManager xx yy` where `xx` is for Picture ID and `yy` is for character name.

Before I end this message I apologize if I mistakenly think that my suggestions above are more precisely aimed at your DarkPlasma_StandImageManager.Js  instead of DarkPlasma_FaceToStand.Js.

Thank you for your attention.

Best regards,
RyanBram

**Comment by elleonard** [comment]
Hi, thank you for the details.

> I propose something more simple and more compatible with Leeryonto's StandPictureManager.js like this:

RMMV's plugin command is not so easy and safety because user must copy and paste command name (sometime it is bad name) and MV editor don't check parameters of command.

e.g.)
`ShowStand 1 FadeRight Right` is right, but user may possibly write `ShowStand FadeRight 1 right`.
MV editor don't check it, then user face error in the middle of game.
(And more, the error is offen to be completely unable to understand.)

So, I think plugin command with multi parameters (especially including mixed types) is not good for users.
(DarkPlasma_StandImageManager.js is too complicated and confusing...It is almost deprecated.)
(By the way, RMMZ's plugin command system is pretty good on that point.)

For that reason, FaceToStand plugin uses switches and variables.

> To improve further compatibility with Leeryonto's StandPictureManager.js maybe the following setup can be added in your plugin setup:

I think RPG Maker plugin must be loosely coupled.

DarkPlasma_FaceToStand.js is responsible for show stand image instead of face image.
It shuld not process messages or character names.
That is not stand image plugin(DarkPlasma_FaceToStand.js, DarkPlasma_StandImageManager.js, etc)'s role.
On that point, Leeryonto's StandPictureManager.js is overcrowding.

If user want to show character name, he/she should use showing name plugin just like DarkPlasma_NameWindow.js.

If user want to link stand image and character name, I propose following way.

Using DarkPlasma_NameWindow.js and DarkPlasma_FaceToStand.js.
Writing additional plugin that links face image and character name, and show character name with linked face image.
(It may able to hook `Window_Message.prototype.findNameWindowTextInfo` and to use `$gameMessage.faceName()` .)

**Comment by RyanBram** [comment]
Hi, Elleonard.

Thank you very much for your explanation.
It is very clear to me if my request will make your DarkPlasma_FaceToStand.js too complicated for simple usage.

I think your 2 solution in the second message above is the best implementation.

Thank you very much for your kindly answer and all of your plugins.

Best regards,
RyanBram
